app_name: Retro-DLP
tag_prefix: v

version:
  source: source/shared/Info.plist
  keys:
    - CFBundleShortVersionString
    - CFBundleVersion
  plists:
    - source/shared/Info.plist

release:
  commit_message: "Version {version}"

targets:
  - name: macOS ppc-i386
    workdir: .
    build:
      - make clean-macOS
      - make macOS
      - cd build/macOS && zip -9 -j retro-dlp-ppc-i386.zip ppc-i386/retro-dlp cacert.pem
    artifact: build/macOS/retro-dlp-ppc-i386.zip
    asset_name: Retro-DLP-{version}-macOS-ppc-i386.zip

  - name: macOS x86_64-arm64
    workdir: .
    build:
      - make macOS
      - cd build/macOS && zip -9 -j retro-dlp-x86_64-arm64.zip x86_64-arm64/retro-dlp cacert.pem
    artifact: build/macOS/retro-dlp-x86_64-arm64.zip
    asset_name: Retro-DLP-{version}-macOS-x86_64-arm64.zip

  - name: iOS
    workdir: .
    build:
      - make clean-iOS
      - make iOS
      - cd build/iOS && zip -9 retro-dlp-iOS.zip retro-dlp cacert.pem
    artifact: build/iOS/retro-dlp-iOS.zip
    asset_name: Retro-DLP-{version}-iOS.zip

  - name: Linux Library
    workdir: .
    build:
      - make linux
      - source/make/package-library.sh linux build
    artifact: build/linux/retro-dlp-library.zip
    asset_name: Retro-DLP-{version}-linux-library.zip

  - name: macOS Library
    workdir: .
    build:
      - make macOS
      - make validate-apple-artifacts
      - source/make/package-library.sh macOS build
    artifact: build/macOS/retro-dlp-library.zip
    asset_name: Retro-DLP-{version}-macOS-library.zip

  - name: iOS Library
    workdir: .
    build:
      - make iOS
      - make validate-apple-artifacts
      - source/make/package-library.sh iOS build
    artifact: build/iOS/retro-dlp-library.zip
    asset_name: Retro-DLP-{version}-iOS-library.zip
