app_name: Retro-DLP
tag_prefix: v

version:
  source: source/library/shared/Info.plist
  keys:
    - CFBundleShortVersionString
    - CFBundleVersion
  plists:
    - source/library/shared/Info.plist
    - source/gui/macOS/Info.plist
    - source/gui/iOS/Info.plist

release:
  commit_message: "Version {version}"

targets:
  - name: macOS ppc-i386
    workdir: .
    build:
      - make clean-macOS
      - make macOS
      - cd build/macOS && zip -9 -j retro-dlp-ppc-i386.zip ppc-i386/retro-dlp cacert.pem
    artifact: build/macOS/retro-dlp-ppc-i386.zip
    asset_name: Retro-DLP-{version}-macOS-ppc-i386.zip

  - name: iOS
    workdir: .
    build:
      - make clean-iOS
      - make iOS
      - cd build/iOS && zip -9 retro-dlp-iOS.zip retro-dlp cacert.pem
    artifact: build/iOS/retro-dlp-iOS.zip
    asset_name: Retro-DLP-{version}-iOS.zip

  - name: macOS application
    workdir: .
    build:
      - make app-macOS
    artifact: build/apps/macOS/RetroDLP.zip
    asset_name: Retro-DLP-{version}-macOS.zip

  - name: iOS application
    workdir: .
    build:
      - make app-iOS
      - make app-validate
    artifact: build/apps/iOS/RetroDLP.ipa
    asset_name: Retro-DLP-{version}-iOS.ipa

  - name: Linux Library
    workdir: .
    build:
      - make linux
      - make/package-library.sh linux build
    artifact: build/linux/retro-dlp-library.zip
    asset_name: Retro-DLP-{version}-linux-library.zip

  - name: macOS Library
    workdir: .
    build:
      - make macOS
      - make validate-apple-artifacts
      - make/package-library.sh macOS build
    artifact: build/macOS/retro-dlp-library.zip
    asset_name: Retro-DLP-{version}-macOS-library.zip

  - name: iOS Library
    workdir: .
    build:
      - make iOS
      - make validate-apple-artifacts
      - make/package-library.sh iOS build
    artifact: build/iOS/retro-dlp-library.zip
    asset_name: Retro-DLP-{version}-iOS-library.zip
