#!/bin/sh

set -eu

binary=${1:?usage: cli_test.sh /path/to/retro-dlp /path/to/retro-dlp-tests}
test_binary=${2:?usage: cli_test.sh /path/to/retro-dlp /path/to/retro-dlp-tests}
library_dir=$(dirname "$binary")
resolver_library=$library_dir/libretrodlp.a
download_library=$library_dir/libretrodlp-download.a
test_home=$(mktemp -d "${TMPDIR:-/tmp}/retro-dlp-cli-home.XXXXXX")
error_file=${TMPDIR:-/tmp}/retro-dlp-cli-test.$$

cleanup() {
  case "$test_home" in
    "${TMPDIR:-/tmp}"/retro-dlp-cli-home.*) rm -rf -- "$test_home" ;;
  esac
  rm -f "$error_file"
}
trap cleanup EXIT HUP INT TERM
HOME=$test_home
export HOME

fail() {
  echo "FAIL: $1" >&2
  exit 1
}

nm "$binary" | grep -q ' cJSON_Parse$' || \
  fail "Linux binary does not contain cJSON"
nm "$binary" | grep -q ' JS_NewRuntime$' || \
  fail "Linux binary does not contain QuickJS"
nm -D "$binary" | grep -q ' U curl_easy_perform' || \
  fail "Linux binary is not linked to libcurl"
nm -D "$binary" | grep -q ' U SHA256' || \
  fail "Linux binary is not linked to OpenSSL SHA-256"
nm -D "$binary" | grep -q ' U SHA1' || \
  fail "Linux binary is not linked to OpenSSL SHA-1"
if strings "$binary" | grep -q 'This file was automatically generated by https://github.com/yt-dlp/ejs'; then
  fail "release binary contains the EJS JavaScript bundle"
fi
if nm "$binary" | grep -q 'retro_dlp_run_self_tests'; then
  fail "release binary contains the self-test harness"
fi
test -f "$resolver_library" || fail "resolver library was not built"
test -f "$download_library" || fail "optional download library was not built"
if ar t "$resolver_library" | grep -Eq \
    '^(main|cli|cli_options|cli_render|cli_assets|cli_asset_store|retrodlp_download|yt_mux)\.o$'; then
  fail "resolver library contains CLI or download objects"
fi
ar t "$resolver_library" | grep -q '^retrodlp_assets\.o$' || \
  fail "resolver library lacks public EJS asset provisioning"
if strings "$resolver_library" | grep -q '/.retro-dlp'; then
  fail "resolver library contains an implicit CLI home-directory path"
fi
if nm -u "$resolver_library" | grep -q 'lsmash'; then
  fail "resolver library depends on L-SMASH"
fi
ar t "$download_library" | grep -q '^retrodlp_download\.o$' || \
  fail "optional download library lacks download orchestration"
ar t "$download_library" | grep -q '^yt_mux\.o$' || \
  fail "optional download library lacks mux orchestration"
if ar t "$download_library" | grep -Eq \
    '^(main|cli|cli_options|cli_render|cli_assets)\.o$'; then
  fail "optional download library contains CLI objects"
fi

help_output=$($binary --help)
printf '%s\n' "$help_output" | grep -q '^Usage: retro-dlp' || \
  fail "--help did not print usage"
printf '%s\n' "$help_output" | grep -q -- '--cookies FILE' || \
  fail "--help did not document --cookies"
printf '%s\n' "$help_output" | grep -q -- '~/.retro-dlp/cookies.txt' || \
  fail "--help did not document the default cookie path"
printf '%s\n' "$help_output" | grep -q -- '-f, --format FORMAT' || \
  fail "--help did not document --format"
printf '%s\n' "$help_output" | grep -q -- '-t, --preset-alias PRESET' || \
  fail "--help did not document --preset-alias"
printf '%s\n' "$help_output" | grep -q -- 'low=18' || \
  fail "--help did not document the low preset"
printf '%s\n' "$help_output" | grep -q -- 'med=135+140/134+140' || \
  fail "--help did not document the med preset"
printf '%s\n' "$help_output" | \
  grep -q -- 'high=137+140/136+140' || \
  fail "--help did not document the high preset"
printf '%s\n' "$help_output" | grep -q -- '-F, --list-formats' || \
  fail "--help did not document --list-formats"
printf '%s\n' "$help_output" | grep -q -- '--flat-playlist' || \
  fail "--help did not document --flat-playlist"
printf '%s\n' "$help_output" | grep -q -- '-j, --dump-json' || \
  fail "--help did not document --dump-json"
printf '%s\n' "$help_output" | grep -q -- 'sanitized video title plus .mp4' || \
  fail "--help did not document the title-based output filename"
if printf '%s\n' "$help_output" | grep -Eq -- '--size|--no-download|--test'; then
  fail "--help retained a removed option"
fi

if $binary -f best YE7VzlLtp-4 2>"$error_file"; then
  fail "unsupported format syntax returned success"
fi

if $binary -t ultra YE7VzlLtp-4 2>"$error_file"; then
  fail "unknown preset alias returned success"
fi
grep -q 'available presets are high, med, low' "$error_file" || \
  fail "unknown preset alias did not list the available presets"

if $binary -t low -f 18 YE7VzlLtp-4 2>"$error_file"; then
  fail "combined preset and exact format returned success"
fi
grep -q -- '--format and --preset-alias cannot be combined' "$error_file" || \
  fail "preset/format conflict did not explain the error"

version_output=$($binary --version)
printf '%s\n' "$version_output" | \
  grep -Eq '^retro-dlp [0-9]+\.[0-9]+\.[0-9]+ \(Linux\)$' || \
  fail "unexpected --version output: $version_output"

asset_status=$($binary assets status)
printf '%s\n' "$asset_status" | grep -q '"installed":[[:space:]]*false' || \
  fail "fresh asset status was not missing"
asset_install=$($binary assets install)
printf '%s\n' "$asset_install" | grep -q '"installed":[[:space:]]*true' || \
  fail "asset install did not validate both EJS files"

asset_dir=$test_home/.retro-dlp/cache/assets/ejs/0.8.0
RETRO_DLP_TEST_EJS_DIR=$asset_dir
export RETRO_DLP_TEST_EJS_DIR
cp "$asset_dir/core.min.js" "$asset_dir/core.saved"
printf 'corrupt' > "$asset_dir/core.min.js"
asset_status=$($binary assets status)
printf '%s\n' "$asset_status" | grep -q '"status":[[:space:]]*"RDLP_ERROR_EJS_ASSETS_CORRUPT"' || \
  fail "truncated EJS asset was accepted"
cp "$asset_dir/core.saved" "$asset_dir/core.min.js"
printf 'X' | dd of="$asset_dir/core.min.js" bs=1 seek=100 conv=notrunc 2>/dev/null
asset_status=$($binary assets status)
printf '%s\n' "$asset_status" | grep -q '"status":[[:space:]]*"RDLP_ERROR_EJS_ASSETS_CORRUPT"' || \
  fail "wrong-hash EJS asset was accepted"
cp "$asset_dir/core.saved" "$asset_dir/core.min.js"
dd if=/dev/zero bs=1 count=1 >> "$asset_dir/core.min.js" 2>/dev/null
asset_status=$($binary assets status)
printf '%s\n' "$asset_status" | grep -q '"status":[[:space:]]*"RDLP_ERROR_EJS_ASSETS_CORRUPT"' || \
  fail "oversized EJS asset was accepted"
mv "$asset_dir/core.saved" "$asset_dir/core.min.js"
printf 'partial' > "$asset_dir/core.min.js.tmp.interrupted"
asset_status=$($binary assets status)
printf '%s\n' "$asset_status" | grep -q '"installed":[[:space:]]*true' || \
  fail "interrupted temporary asset replaced the installation"
mkdir -p "$test_home/.retro-dlp/cache/assets/ejs/0.7.0"
printf 'wrong version' > \
  "$test_home/.retro-dlp/cache/assets/ejs/0.7.0/core.min.js"

self_test_output=$($test_binary)
printf '%s\n' "$self_test_output" | grep -q '^PASS: cJSON$' || \
  fail "test binary did not pass cJSON"
printf '%s\n' "$self_test_output" | grep -q '^PASS: QuickJS$' || \
  fail "test binary did not pass QuickJS"
printf '%s\n' "$self_test_output" | grep -q '^PASS: OpenSSL SHA-256$' || \
  fail "test binary did not pass OpenSSL SHA-256"
printf '%s\n' "$self_test_output" | \
  grep -q '^PASS: cookies, SAPISID authorization, redaction, and cache isolation$' || \
  fail "test binary did not pass cookie authentication fixtures"
printf '%s\n' "$self_test_output" | grep -q '^PASS: EJS 0.8.0' || \
  fail "test binary did not run the downloaded EJS assets"
printf '%s\n' "$self_test_output" | grep -q '^PASS: video ID parsing' || \
  fail "test binary did not pass video ID parsing"
printf '%s\n' "$self_test_output" | grep -q '^PASS: playlist ID parsing$' || \
  fail "test binary did not pass playlist ID parsing"
printf '%s\n' "$self_test_output" | \
  grep -q '^PASS: playlist collection JSON parsing$' || \
  fail "test binary did not pass playlist collection JSON parsing"
printf '%s\n' "$self_test_output" | \
  grep -q '^PASS: playlist bootstrap, pagination, duplicate, and error fixtures$' || \
  fail "test binary did not pass playlist page fixtures"
printf '%s\n' "$self_test_output" | \
  grep -q '^PASS: owned-result allocation failure contracts$' || \
  fail "test binary did not pass owned-result allocation failures"
printf '%s\n' "$self_test_output" | \
  grep -q '^PASS: pagination token allocation failure contract$' || \
  fail "test binary did not pass pagination allocation failure"
printf '%s\n' "$self_test_output" | \
  grep -q '^PASS: deterministic player fixtures$' || \
  fail "test binary did not pass deterministic player fixtures"
printf '%s\n' "$self_test_output" | grep -q '^PASS: retro-dlp self-test$' || \
  fail "test binary did not report success"

if $binary --not-an-option 2>"$error_file"; then
  fail "unsupported arguments returned success"
fi
grep -q '^retro-dlp: unknown option "--not-an-option"$' "$error_file" || \
  fail "unknown option did not report its name"
grep -q '^retro-dlp: try "retro-dlp --help" for usage$' "$error_file" || \
  fail "unknown option did not provide a usage hint"

if $binary --cokies-default YE7VzlLtp-4 2>"$error_file"; then
  fail "misspelled option returned success"
fi
grep -q '^retro-dlp: did you mean "--cookies-default"?$' "$error_file" || \
  fail "misspelled option did not provide a suggestion"

if $binary --flat-playlist YE7VzlLtp-4 2>"$error_file"; then
  fail "--flat-playlist accepted a video ID"
fi
grep -q '^retro-dlp: RDLP_ERROR_INVALID_PLAYLIST (-130)$' \
  "$error_file" || fail "invalid flat-playlist input was misclassified"

if $binary --flat-playlist \
    'https://www.youtube.com/feed/playlists' 2>"$error_file"; then
  fail "account playlist collection did not require cookies"
fi
grep -q '^retro-dlp: RDLP_ERROR_COOKIES_REJECTED (-450)$' \
  "$error_file" || fail "account playlist collection lacked cookie guidance"

invalid_cookie_file=$test_home/invalid-cookies.txt
printf '%s\n' '# Netscape HTTP Cookie File' > "$invalid_cookie_file"
printf '%s\n' \
  '.youtube.com	TRUE	/	TRUE	4102444800	PREF	hl=en' >> \
  "$invalid_cookie_file"
if $binary --cookies "$invalid_cookie_file" --dump-json YE7VzlLtp-4 \
    2>"$error_file"; then
  fail "incomplete authentication cookies returned success"
fi
grep -q '^retro-dlp: RDLP_ERROR_COOKIES_REJECTED (-450)$' \
  "$error_file" || fail "invalid authentication cookies were misclassified"
if grep -q 'hl=en' "$error_file"; then
  fail "cookie value was written to an error message"
fi

cp "$invalid_cookie_file" "$test_home/.retro-dlp/cookies.txt"
chmod 600 "$test_home/.retro-dlp/cookies.txt"
if $binary --cookies-default --dump-json YE7VzlLtp-4 2>"$error_file"; then
  fail "incomplete default authentication cookies returned success"
fi
grep -q '^retro-dlp: RDLP_ERROR_COOKIES_REJECTED (-450)$' \
  "$error_file" || fail "--cookies-default did not use ~/.retro-dlp/cookies.txt"
if grep -q 'YE7VzlLtp-4.*cookie' "$error_file"; then
  fail "video ID was misclassified as an explicit cookie path"
fi

asset_remove=$($binary assets remove)
printf '%s\n' "$asset_remove" | grep -q '"installed":[[:space:]]*false' || \
  fail "asset remove did not remove EJS files"
asset_status=$($binary assets status)
printf '%s\n' "$asset_status" | grep -q '"status":[[:space:]]*"RDLP_ERROR_EJS_ASSETS_MISSING"' || \
  fail "wrong-version asset directory was accepted"

echo "PASS: Linux CLI"
