#!/bin/sh

set -eu

binary=${1:?usage: cli_test.sh /path/to/retro-dlp}
test_cookie_file=${2:-}
test_home=$(mktemp -d "${TMPDIR:-/tmp}/retro-dlp-cli-home.XXXXXX")
error_file=${TMPDIR:-/tmp}/retro-dlp-cli-test.$$

cleanup() {
  case "$test_home" in
    "${TMPDIR:-/tmp}"/retro-dlp-cli-home.*) rm -rf -- "$test_home" ;;
  esac
  rm -f "$error_file"
}
trap cleanup EXIT HUP INT TERM
HOME=$test_home
export HOME

fail() {
  echo "FAIL: $1" >&2
  exit 1
}

nm "$binary" | grep -q ' cJSON_Parse$' || \
  fail "Linux binary does not contain cJSON"
nm "$binary" | grep -q ' JS_NewRuntime$' || \
  fail "Linux binary does not contain QuickJS"
nm -D "$binary" | grep -q ' U curl_easy_perform' || \
  fail "Linux binary is not linked to libcurl"
nm -D "$binary" | grep -q ' U SHA256' || \
  fail "Linux binary is not linked to OpenSSL SHA-256"
nm -D "$binary" | grep -q ' U SHA1' || \
  fail "Linux binary is not linked to OpenSSL SHA-1"
if strings "$binary" | grep -q 'This file was automatically generated by https://github.com/yt-dlp/ejs'; then
  fail "release binary contains the EJS JavaScript bundle"
fi

help_output=$($binary --help)
printf '%s\n' "$help_output" | grep -q '^Usage: retro-dlp' || \
  fail "--help did not print usage"
printf '%s\n' "$help_output" | grep -q -- '--cookies \[FILE\]' || \
  fail "--help did not document --cookies"
printf '%s\n' "$help_output" | grep -q -- '~/.retro-dlp/cookies.txt' || \
  fail "--help did not document the default cookie path"
printf '%s\n' "$help_output" | grep -q -- '--size SIZE' || \
  fail "--help did not document --size"
printf '%s\n' "$help_output" | grep -q -- 'default: 720p' || \
  fail "--help did not document the default size"

if $binary --size 480p 2>"$error_file"; then
  fail "--size without a video returned success"
fi
if $binary --size 480 YE7VzlLtp-4 2>"$error_file"; then
  fail "invalid --size returned success"
fi
grep -q '^retro-dlp: unsupported arguments$' "$error_file" || \
  fail "invalid --size was not rejected"

version_output=$($binary --version)
[ "$version_output" = "retro-dlp 0.1.0 (Linux)" ] || \
  fail "unexpected --version output: $version_output"

asset_status=$($binary assets status)
printf '%s\n' "$asset_status" | grep -q '"installed":[[:space:]]*false' || \
  fail "fresh asset status was not missing"
asset_install=$($binary assets install)
printf '%s\n' "$asset_install" | grep -q '"installed":[[:space:]]*true' || \
  fail "asset install did not validate both EJS files"

asset_dir=$test_home/.retro-dlp/cache/assets/ejs/0.8.0
cp "$asset_dir/core.min.js" "$asset_dir/core.saved"
printf 'corrupt' > "$asset_dir/core.min.js"
asset_status=$($binary assets status)
printf '%s\n' "$asset_status" | grep -q '"status":[[:space:]]*"corrupt"' || \
  fail "truncated EJS asset was accepted"
cp "$asset_dir/core.saved" "$asset_dir/core.min.js"
printf 'X' | dd of="$asset_dir/core.min.js" bs=1 seek=100 conv=notrunc 2>/dev/null
asset_status=$($binary assets status)
printf '%s\n' "$asset_status" | grep -q '"status":[[:space:]]*"corrupt"' || \
  fail "wrong-hash EJS asset was accepted"
cp "$asset_dir/core.saved" "$asset_dir/core.min.js"
dd if=/dev/zero bs=1 count=1 >> "$asset_dir/core.min.js" 2>/dev/null
asset_status=$($binary assets status)
printf '%s\n' "$asset_status" | grep -q '"status":[[:space:]]*"corrupt"' || \
  fail "oversized EJS asset was accepted"
mv "$asset_dir/core.saved" "$asset_dir/core.min.js"
printf 'partial' > "$asset_dir/core.min.js.tmp.interrupted"
asset_status=$($binary assets status)
printf '%s\n' "$asset_status" | grep -q '"installed":[[:space:]]*true' || \
  fail "interrupted temporary asset replaced the installation"
mkdir -p "$test_home/.retro-dlp/cache/assets/ejs/0.7.0"
printf 'wrong version' > \
  "$test_home/.retro-dlp/cache/assets/ejs/0.7.0/core.min.js"

if [ -n "$test_cookie_file" ]; then
  self_test_output=$($binary --cookies "$test_cookie_file" --test)
else
  self_test_output=$($binary --test)
fi
printf '%s\n' "$self_test_output" | grep -q '^PASS: cJSON$' || \
  fail "--test did not pass cJSON"
printf '%s\n' "$self_test_output" | grep -q '^PASS: QuickJS$' || \
  fail "--test did not pass QuickJS"
printf '%s\n' "$self_test_output" | grep -q '^PASS: OpenSSL SHA-256$' || \
  fail "--test did not pass OpenSSL SHA-256"
printf '%s\n' "$self_test_output" | \
  grep -q '^PASS: cookies, SAPISID authorization, redaction, and cache isolation$' || \
  fail "--test did not pass cookie authentication fixtures"
printf '%s\n' "$self_test_output" | grep -q '^PASS: EJS 0.8.0' || \
  fail "--test did not run the downloaded EJS assets"
printf '%s\n' "$self_test_output" | grep -q '^PASS: video ID parsing' || \
  fail "--test did not pass video ID parsing"
printf '%s\n' "$self_test_output" | \
  grep -q '^PASS: deterministic player and HTTP classification fixtures$' || \
  fail "--test did not pass deterministic player fixtures"
printf '%s\n' "$self_test_output" | grep -q '^PASS: player API response' || \
  fail "--test did not pass the live player API test"
printf '%s\n' "$self_test_output" | \
  grep -q '^PASS: media byte range (YE7VzlLtp-4,' || \
  fail "--test did not pass the YE7VzlLtp-4 media byte-range test"
printf '%s\n' "$self_test_output" | \
  grep -q '^PASS: media byte range (-_x6t4CaPzo,' || \
  fail "--test did not pass the -_x6t4CaPzo media byte-range test"
printf '%s\n' "$self_test_output" | grep -q '^PASS: retro-dlp self-test$' || \
  fail "--test did not report success"

resolve_output=$($binary --no-download "https://youtu.be/YE7VzlLtp-4" \
  2>"$error_file")
grep -q '^retro-dlp: resolving video information$' "$error_file" || \
  fail "video resolution did not announce its start"
grep -q '^retro-dlp: fetching web player configuration$' "$error_file" || \
  fail "video resolution did not report its bootstrap request"
grep -q '^retro-dlp: requesting video metadata$' "$error_file" || \
  fail "video resolution did not report its metadata request"
grep -q '^retro-dlp: selecting a progressive MP4 stream$' "$error_file" || \
  fail "video resolution did not report format selection"
printf '%s\n' "$resolve_output" | grep -q '"itag":[[:space:]]*[0-9]' || \
  fail "video resolution did not return an itag"
printf '%s\n' "$resolve_output" | grep -Eq '"height":[[:space:]]*(360|480|720)' || \
  fail "default video resolution exceeded 720p"
printf '%s\n' "$resolve_output" | grep -q 'googlevideo.com' || \
  fail "video resolution did not return a Google Video URL"
if printf '%s\n' "$resolve_output" | grep -q '"probe"'; then
  fail "--no-download unexpectedly performed a probe"
fi
[ -f "$test_home/.retro-dlp/cache/v1/client-manifest/builtin-v2.entry" ] || \
  fail "resolver did not populate the client-manifest cache"
[ -f "$test_home/.retro-dlp/cache/v1/successful-client/last-anonymous.entry" ] || \
  fail "resolver did not populate the successful-client cache"

if [ -n "$test_cookie_file" ]; then
  python3 source/linux/test/yt_dlp_oracle.py "$binary" \
    inspiration/yt-dlp/yt_dlp/__main__.py "$test_cookie_file"
else
  python3 source/linux/test/yt_dlp_oracle.py "$binary" \
    inspiration/yt-dlp/yt_dlp/__main__.py
fi

if $binary --not-an-option 2>"$error_file"; then
  fail "unsupported arguments returned success"
fi
grep -q '^retro-dlp: unsupported arguments$' "$error_file" || \
  fail "unsupported arguments did not report an error"

invalid_cookie_file=$test_home/invalid-cookies.txt
printf '%s\n' '# Netscape HTTP Cookie File' > "$invalid_cookie_file"
printf '%s\n' \
  '.youtube.com	TRUE	/	TRUE	4102444800	PREF	hl=en' >> \
  "$invalid_cookie_file"
if $binary --cookies "$invalid_cookie_file" --no-download YE7VzlLtp-4 \
    2>"$error_file"; then
  fail "incomplete authentication cookies returned success"
fi
grep -q '^retro-dlp: YouTube authentication cookies are missing, expired, or invalid$' \
  "$error_file" || fail "invalid authentication cookies were misclassified"
if grep -q 'hl=en' "$error_file"; then
  fail "cookie value was written to an error message"
fi

cp "$invalid_cookie_file" "$test_home/.retro-dlp/cookies.txt"
chmod 600 "$test_home/.retro-dlp/cookies.txt"
if $binary --cookies --no-download YE7VzlLtp-4 2>"$error_file"; then
  fail "incomplete default authentication cookies returned success"
fi
grep -q '^retro-dlp: YouTube authentication cookies are missing, expired, or invalid$' \
  "$error_file" || fail "--cookies did not use ~/.retro-dlp/cookies.txt"
if grep -q 'YE7VzlLtp-4.*cookie' "$error_file"; then
  fail "video ID was misclassified as an explicit cookie path"
fi

asset_remove=$($binary assets remove)
printf '%s\n' "$asset_remove" | grep -q '"installed":[[:space:]]*false' || \
  fail "asset remove did not remove EJS files"
asset_status=$($binary assets status)
printf '%s\n' "$asset_status" | grep -q '"status":[[:space:]]*"missing"' || \
  fail "wrong-version asset directory was accepted"

echo "PASS: Linux CLI"
